export const actionTypes = {
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  VERIFY_ACCOUNT: "VERIFY_ACCOUNT",
  RESEND_ACCOUNT_VERIFICATION_OTP: "RESEND_ACCOUNT_VERIFICATION_OTP",
  LOGIN_USER: "LOGIN_USER",
  FORGET_PASSWORD: "FORGET_PASSWORD",
  RECOVER_ACCOUNT: "RECOVER_ACCOUNT",
  GET_NEW_RECOVERY_OTP: "GET_NEW_RECOVERY_OTP",
};
